import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { AuthProvider } from "./AuthProvider";
import NextTopLoader from "nextjs-toploader"
import { Toaster as SonnerToaster } from "sonner";
import { Toaster } from "@/components/ui/toaster";
import PageContainer from "@/components/page-container";

import { Roboto } from 'next/font/google'
import { Suspense } from "react";
import Spinner from "@/components/spinner";

const roboto = Roboto({
    weight: '400',
    subsets: ['latin'],
})
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default async function RootLayout({ children }: { children: React.ReactNode }) {

    return (
        <>
            <html lang="en" suppressHydrationWarning>
                <head />
                <body className={roboto.className + "font-exo_2"}>
                    <AuthProvider>
                        <NextTopLoader />
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="system"
                            enableSystem
                            disableTransitionOnChange
                        >
                            <PageContainer>
                                {/* <Suspense fallback={<Spinner />}> */}
                                    {children}
                                {/* </Suspense > */}
                            </PageContainer>
                            <SonnerToaster />
                            <Toaster />
                        </ThemeProvider>
                    </AuthProvider>
                </body>
            </html>
        </>
    )
}
