import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Header from "./header";
import { AuthProvider } from "./AuthProvider";
import { Suspense } from "react";
import Loading from "./dashboard/loading";
import NextTopLoader from "nextjs-toploader"
import { Toaster as SonnerToaster } from "sonner";
import { Toaster } from "@/components/ui/toaster";
import { headers } from "next/headers";
import { getSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const session = getSession();

    return (
        <>
            <html lang="en" suppressHydrationWarning>
                <head />
                <body className={inter.className + " font-exo_2"}>
                    <AuthProvider>
                        <NextTopLoader />
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="system"
                            enableSystem
                            disableTransitionOnChange
                        >
                            <div className="">
                                <Header />
                                <div className="p-0 container mx-auto">
                                    {children}
                                </div>
                            </div>
                            <SonnerToaster />
                            <Toaster />
                        </ThemeProvider>
                    </AuthProvider>
                </body>
            </html>
        </>
    )
}
