-- CreateTable
CREATE TABLE "UserExam" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "exmId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "UserExam_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "UserExam" ADD CONSTRAINT "UserExam_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserExam" ADD CONSTRAINT "UserExam_exmId_fkey" FOREIGN KEY ("exmId") REFERENCES "Exam"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
